#!/bin/sh

# Immediatly exit if a command fails
set -e

if [ $# -lt 2 ]; then
  echo 1>&2 "usage: deploy {site} {version}"
  exit 2
elif [ $# -gt 2 ]; then
  echo 1>&2 "usage: deploy {site} {version}"
  exit 2
fi

bold=$(tput bold)
normal=$(tput sgr0)
yellow=$(tput setaf 3)
blue=$(tput setaf 4)

site=$1
siteText=${blue}$site${normal}
version=$2
versionText=${yellow}$version${normal}
current=$(ssh biblys "cd ~/cloud/$site && git describe --tags")
currentText=${yellow}$current${normal}

echo "> Deploying version $version on site $site..."

echo "> Upgrading $siteText from $currentText to $versionText..."

echo "> Fetching latest changes from repository..."
ssh biblys "cd ~/cloud/$site && git fetch"

echo "> Changing to tag $versionText..."
ssh biblys "cd ~/cloud/$site && git checkout $version"

echo "> Installing dependencies..."
ssh biblys "cd ~/cloud/$site && composer install"

echo "> ✅  Version $versionText has been deployed on $siteText"
