#!/bin/sh

# Immediatly exit if a command fails
set -e

if [ $# -lt 1 ]; then
  echo 1>&2 "usage: deploy-all {version}"
  exit 2
elif [ $# -gt 1 ]; then
  echo 1>&2 "usage: deploy-all {version}"
  exit 2
fi

sites=$(ssh biblys "ls cloud")
version=$1

for site in $sites
do
  echo
  echo "> Site $site"
  ./deploy $site $version
done
