#!/bin/sh

# Immediatly exit if a command fails
set -e

# Ask for site
printf "Site: "
read site

# Ask for version
printf "Version: "
read version

echo "> Deploying version $version on site $site..."

echo "> Fetching latest changes from repository..."
ssh biblys "cd ~/cloud/$site && git fetch"

echo "> Changing to tag $version..."
ssh biblys "cd ~/cloud/$site && git checkout $version"

echo "> Installing dependencies..."
ssh biblys "cd ~/cloud/$site && composer install"
